import math

STANDARD_GRAVITY_M_PER_S2: float = 9.80665
TSUNAMI_SOLVER_EARTH_RADIUS_M: float = 6.37e6
TSUNAMI_MODEL_EARTH_RADIUS_KM: float = 6370.8
MEAN_EARTH_RADIUS_KM: float = 6371.0
MEAN_EARTH_KILOMETERS_PER_DEGREE: float = MEAN_EARTH_RADIUS_KM * math.pi / 180.0
FAULT_PLANE_KILOMETERS_PER_DEGREE: float = 111.0
MAXOLA_GRID_KILOMETERS_PER_DEGREE: float = 111.1994
