version: 2
updates:
    - package-ecosystem: "uv"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          dev:
              patterns: ["*"]
              exclude-patterns: ["ruff", "mypy"]

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          actions:
              patterns: ["*"]

    - package-ecosystem: "docker"
      directory: "/deploy"
      schedule:
          interval: "weekly"
      groups:
          dockerfile:
              patterns: ["*"]

    - package-ecosystem: "docker"
      directory: "/.devcontainer"
      schedule:
          interval: "weekly"
      groups:
          dockerfile:
              patterns: ["*"]
