#!/bin/csh -f

set i2file = cortado.i2
#set cmtfile = ../meca.dat

# Epicentro
#set loc = -78.00/-12.00
set loc = $1
set ttt1grd = ttt.b
ttt_client $i2file -E$loc -T$ttt1grd -VL
gmt grdmath $ttt1grd=bf 1.0 MUL = $ttt1grd=bf

