name: "Pre-commit"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: ["main"]

jobs:
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.8.1
    with:
      env: '["py39", "py310", "py311", "py312"]'
      os: ubuntu-latest
