name: OpenSSF Scorecard

on:
    branch_protection_rule: {}
    schedule:
        - cron: "0 4 * * 6"
    workflow_dispatch:

permissions: {}

jobs:
    analysis:
        name: Scorecard
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            security-events: write
        steps:
            - uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - uses: ossf/scorecard-action@v2.4.3
              with:
                  results_file: results.sarif
                  results_format: sarif
                  publish_results: true

            - name: Upload results
              uses: actions/upload-artifact@v7
              with:
                  name: results.sarif
                  path: results.sarif
